/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpenRouteImport } from './routes/open'
import { Route as ApiGranthRouteImport } from './routes/api/granth'
import { Route as ApiMediaRouteImport } from './routes/api/media'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenRoute = OpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGranthRoute = ApiGranthRouteImport.update({
  id: '/api/granth',
  path: '/api/granth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/open': typeof OpenRoute
  '/api/granth': typeof ApiGranthRoute
  '/api/media': typeof ApiMediaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/open': typeof OpenRoute
  '/api/granth': typeof ApiGranthRoute
  '/api/media': typeof ApiMediaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/open': typeof OpenRoute
  '/api/granth': typeof ApiGranthRoute
  '/api/media': typeof ApiMediaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/open' | '/api/granth' | '/api/media'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/open' | '/api/granth' | '/api/media'
  id: '__root__' | '/' | '/open' | '/api/granth' | '/api/media'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpenRoute: typeof OpenRoute
  ApiGranthRoute: typeof ApiGranthRoute
  ApiMediaRoute: typeof ApiMediaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open': {
      id: '/open'
      path: '/open'
      fullPath: '/open'
      preLoaderRoute: typeof OpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/granth': {
      id: '/api/granth'
      path: '/api/granth'
      fullPath: '/api/granth'
      preLoaderRoute: typeof ApiGranthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpenRoute: OpenRoute,
  ApiGranthRoute: ApiGranthRoute,
  ApiMediaRoute: ApiMediaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
